version: '3'

services:
  customer-portal-ui:
    container_name: customer-portal-ui
    build:
      context: ./apps/customer-portal-ui
      dockerfile: dockerfile
    environment:
      NEXT_PUBLIC_ANALYTICS_SERVICE_API: "http://localhost:4000"
    volumes:
      - ./apps/customer-portal-ui/src:/app/src
      - ./apps/customer-portal-ui/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  analytics_logs: