import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Geist, Geist_Mono, IBM_Plex_Sans } from "next/font/google";
import "@/styles/globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
  variable: "--font-ibm-plex-sans", // Optional: Define a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="snap-y snap-mandatory">
      <body
        className={`${ibmPlexSans} ${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        {/* <Header /> */}
        <main className="flex-1 ">
         {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
